---
- name: "{{ role_name }} | {{ task.name }} | Ensure the workspaces folder for VSCode"
  ansible.builtin.file:
    path: "{{ vscode_workspaces_folder }}"
    state: directory
    mode: '0750'
  register: result_vscode_workspaces_folder
  when: result_install_vscode is success

- name: "{{ role_name }} | {{ task.name }} | Locate the {{ vscode_workspaces_config_file }} file of VSCode"
  ansible.builtin.find:
    paths: "{{ vscode_workspaces_folder }}"
    recurse: true
    patterns: "{{ vscode_workspaces_config_file }}"
  register: result_vscode_workspaces_file
  when: result_vscode_workspaces_folder is success

- name: "{{ role_name }} | {{ task.name }} | First execution of VSCode"
  ansible.builtin.debug:
    msg:
      - "If VSCode was just installed, is necessary to open it to create the initial configuration."
      - "Then add at least one folder in your VSCode workspace to create the workspaces configurations file."
      - "VSCode Menu: File -> Add Folder to Workspace..."
  when: result_vscode_workspaces_file.matched == 0

- name: "{{ role_name }} | {{ task.name }} | Ensure Workspace folders are set in VSCode"
  ansible.builtin.command:
    chdir: "{{ role_path }}/files"
    argv:
      - "{{ ansible_python_interpreter }}"
      - vscode_settings.py
      - "{{ item.action }}"
      - "{{ result_vscode_workspaces_file.files[0].path }}"
      - "folders"
      - "path"
      - "{{ item.path }}"
  loop: "{{ vscode_workspaces }}"
  register: result_workspaces_reference
  changed_when: result_workspaces_reference.rc == 1
  failed_when: result_workspaces_reference.rc in [2,3]
  when:
    - item.enabled
    - item.state == "directory"
    - result_vscode_workspaces_file.matched == 1
...
