---
# This approach makes the module more dynamic and flexible.
# Please, don't edit this file.
# You can control everything on "default/main.yml" and
# "vars". Unless you are developing something new here.

- name: "{{ role_name }} | extra_calls | Load vars for {{ object.name }}"
  include_vars: "{{ object.name }}.yml"
  when: object.name in group_names

- name: "{{ role_name }} | extra_calls | Load tasks for {{ object.name }}"
  include_tasks: "{{ object.name }}.yml"
  when: object.name in group_names
...
