---
# This file has the custom configurations for configure_vscode task.

vscode_workspaces_folder: "{{ ansible_facts['user_dir'] }}/.config/Code/Workspaces"
vscode_workspaces_config_file: "workspace.json"
...
